# Generated by Django 4.2.13 on 2024-07-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={},
        ),
    ]
