# Generated by Django 4.2.13 on 2024-08-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document_Details', '0002_alter_tracking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={'managed': False},
        ),
    ]
