# Generated by Django 4.2.13 on 2024-08-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('depart_id', models.CharField(db_column='Depart_ID', max_length=10, primary_key=True, serialize=False)),
                ('depart_name', models.CharField(blank=True, db_column='Depart_Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.CharField(db_column='Document_ID', max_length=10, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, db_column='Document_Type', max_length=10, null=True)),
                ('generation_date', models.DateField(blank=True, db_column='Generation_Date', null=True)),
                ('document_time', models.DateTimeField(blank=True, db_column='Document_Time', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('link', models.CharField(blank=True, db_column='Link', max_length=250, null=True)),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(db_column='Employee_ID', max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=10, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('officers_id', models.CharField(db_column='Officers_ID', max_length=10, primary_key=True, serialize=False)),
                ('officers_name', models.CharField(blank=True, db_column='Officers_Name', max_length=10, null=True)),
            ],
            options={
                'db_table': 'officers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.CharField(db_column='Status_ID', max_length=10, primary_key=True, serialize=False)),
                ('status_name', models.CharField(blank=True, db_column='Status_Name', max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, db_column='Full_Name', max_length=50, null=True)),
                ('forwarded_date', models.DateField(blank=True, db_column='Forwarded_Date', null=True)),
                ('forwarded_time', models.DateTimeField(blank=True, db_column='Forwarded_Time', null=True)),
            ],
            options={
                'db_table': 'tracking',
                'managed': False,
            },
        ),
    ]
